### ISSUE TITLE
ModuleNotFoundError: No module named 'chardet'

### ISSUE THREAD

**Issue by souravbadami** [cseas/ocr-table#3]
```
Traceback (most recent call last):
  File "pdf_miner.py", line 8, in <module>
    from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
  File "/anonymized/ocr-table/venv3/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 5, in <module>
    from .cmapdb import CMapDB
  File "/anonymized/ocr-table/venv3/lib/python3.7/site-packages/pdfminer/cmapdb.py", line 24, in <module>
    from .psparser import PSStackParser
  File "/anonymized/ocr-table/venv3/lib/python3.7/site-packages/pdfminer/psparser.py", line 11, in <module>
    from .utils import choplist
  File "/anonymized/ocr-table/venv3/lib/python3.7/site-packages/pdfminer/utils.py", line 13, in <module>
    import chardet  # For str encoding detection in Py3
ModuleNotFoundError: No module named 'chardet'
```

**Comment by cseas** [comment]
Merging PR #4 to fix this
